- pom.xml
* 2.7.14 fixes CVE-2012-6153 and CVE-2014-3577
> Update CXF from 2.7.11 to 2.7.14

- pom.xml
> Update Spring from 3.2.11.RELEASE to 3.2.12.RELEASE

- pom.xml
> upgrade io.netty

- pom.xml
> upgrade httpclient

- pom.xml
> upgrade hibernate

- pom.xml
> upgraded hibernate-validator

- pom.xml
> upgraded hornetq

- pom.xml
> upgrade org.jboss.ironjacamar

- pom.xml
> upgrade org.jboss.jbossts

- pom.xml
> upgrade org.jboss.marshalling

- pom.xml
> upgrade jboss-jsp-api_2.2_spec

- pom.xml
> upgrade org.jboss.weld

- pom.xml
> upgrade org.jboss.xnio

- pom.xml
> upgrade org.apache.maven

- pom.xml
> upgrade org.jboss.remoting3

- pom.xml
> upgrade org.infinispan

- pom.xml
for alignment to EAP 6.4.0.CR1
> upgraded org.codehaus.plexus

- pom.xml
> upgraded org.eclipse.jdt.core.compiler

- pom.xml
> upgrade hornetq

- pom.xml
> upgraded hibernate search

- pom.xml
alignment to EAP 6.4.0.CR1
the version 4.5.3.Final is not compatible with EAP 6 so we have to go back to 4.4.6.Final
> upgraded to a EAP 6 compatible version

- ip-bom/pom.xml
- pom.xml
added also some artifacts used in kie-platform.bom
> upgraded version.org.ops4j.pax.exam to align with kie-platform.bom

- ip-bom/pom.xml
removes the duplicate of org.apache.maven:maven-plugin-api of PR 196
> removed duplicated maven-plugin-api

- ip-bom/pom.xml
- pom.xml
org.reflections is the successor of scannotations (better api + better independent of app server and JSE)
> Add org.reflections 0.9.10

- pom.xml
to align to EAP 6.4.2 and finally EAP 6.4.3 this component has to be downgraded.
a build for droolsjbom-jbpm were done and everything worked properly
> downgrade org.apache.ws.xmlschema to align with EAP 6.4.3

- pom.xml
to align to EAP 6.4.2 and finally EAP 6.4.3 this component has to be downgraded.
a build for droolsjbom-jbpm were done and everything worked properly
> downgrade org.jboss.xnio to align with EAP 6.4.3

- ip-bom/pom.xml
- pom.xml
We are using these directly as well, so we need them in the depMgmt.
> Add plexus and sisu dependencies (transive deps of maven)

- ip-bom/pom.xml
- pom.xml
this will fix the BZ 1312172 and 1312175
> upgraded version.org.beanshell from 2.0b5 to 2.0b6

- ip-bom/pom.xml
- pom.xml
The same PR have been merged to origin/6.0.x as https://github.com/jboss-integration/jboss-integration-platform-bom/pull/266
So this should also be merged to master as well.
> BZ-1309248 Add keycloak into jboss-integration-bom

- pom.xml
Upgrade deltaspike core to 1.5.1
> Upgrade deltaspike core to 1.5.1

- pom.xml
(cherry picked from commit f15dd654485fe77b5a79c7b443669a2913973abf)
> Upgrade protobuf from2.5.0 to 2.6.0 (Backport)

- ip-bom/pom.xml
- pom.xml
* the classfilewriter is needed by the weld-environment
> Upgrade Weld from 1.1.31.Final to 2.3.3.Final and Weld API from 1.1.Final to 2.3.SP1

- pom.xml
upgraded
org.jasypt.jasypt
org.jboss.shrinkwrap.descriptors
org.jboss.xnio
org.jgroups
> aligned different versions to JBEAP 7.0.0.ER7

- pom.xml
* main improvement is the compatibility with JDK 9 Verona project
* bunch of plugin upgrades as well
> Upgrade jboss-parent from 19 to 20

- pom.xml
updated
org.jboss.jbossts.xts
org.jboss.remoting3
org.jboss.spec.javax.el.jboss-el-api_2.2_spec
org.jboss.spec.javax.servlet.jstl.jboss-jstl-api_1.2_spec
> 1st alignment to JBEAP 6.4.8

- pom.xml
* 2.3.0.Final brings initial support for JDK 9
> Upgrade org.mvel from 2.2.8.Final to 2.3.0.Final

- ip-bom/pom.xml
I have added resteasy-client dependency needed in droolsjbpm/kie-wb-distributions/kie-wb-tests/kie-wb-tests-rest.
> Add resteasy-client dependency

- pom.xml
* this is the version EAP7/WFLY10 uses
> Upgrade jboss-logging from 3.2.1.Final to 3.3.0.Final

- pom.xml
This fixes an issue using jgit on Windows: https://www.eclipse.org/forums/index.php/t/1031740/
> Upgrade jgit to v4.4.1.201607150455-r

- pom.xml
* needed fro GWT 2.8+ compatibility
> Upgrade gson from 1.7.2 to 2.6.2

- ip-bom/pom.xml
- pom.xml
This fixes the problem with compilation of UF Tasks Project.
> [UF-415]: Update xml-apis version to 1.4.01

- pom.xml
- upgrades Roaster version from 2.13.0.Final to 2.19.4.Final
> Roaster version update

- pom.xml
Hey @psiroky , @manstis , 
Here is it a lienzo-core upgrade to latest release. Thanks!
> JBPM-5728: Upgrade lienzo-core to 2.0.284-RELEASE.

- ip-bom-deps-available-test/ip-bom-deps-available-test-settings.xml
- pom.xml
> Upgrade Hibernate deps

- pom.xml
Hey @manstis @psiroky 
This is the promised lienzo upgrade for master branch on the IP BOM :)
Thanks!!
> JBPM-5490: Upgrade lienzo to 2.0.287-RELEASE

- pom.xml
Hey @manstis @psiroky @mbiarnes 
This is the upgrade for Lienzo to version `2.0.291-RELEASE`.
Thanks!
> JBPM-5967: Upgrade to lienzo 2.0.291-RELEASE

- pom.xml
CVE-2014-9970 *Update jasypt version from 1.9.1 to 1.9.2
> CVE-2014-9970 *Update jasypt version from 1.9.1 to 1.9.2

- pom.xml
CVE-2014-9970 RHBRMS-2828 *Update jasypt version from 1.9.1 to 1.9.2 for 7.0.x
> CVE-2014-9970 RHBRMS-2828 *Update jasypt version from 1.9.1 to 1.9.2

- ip-bom/pom.xml
- pom.xml
for alignment of jboss-ip-bom to EAP 7.0.8
> update of dependencies for alignment to EAP 7.0.8

- pom.xml
(cherry picked from commit 5ac0ec299455f1944f01aff47b1c11372ed488be)
> RHBRMS-2952: upgraded mvel version

- pom.xml
(cherry picked from commit 673a9496058309e2c540c7d8a5dbee748ec2f73a)
> upgraded org.jboss.spec.javax.el and org.jboss.spec.javax.jms

- pom.xml
@psiroky 
tested on kie-releases server and the build was OK but UNSTABLE with four tests failing
> Upgrade of dependencies to align with EAP 7.1.0.CR4

- pom.xml
See [JBPM-6700](https://issues.jboss.org/browse/JBPM-6700).
Please **merge after (or same time as) these ones** are being merged:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/668
- https://github.com/kiegroup/kie-wb-common/pull/1351
Thanks!
> JBPM-6700: Upgrade to Lienzo 2.0.295-RELEASE

- ip-bom/pom.xml
- pom.xml
tested with all updates on RHBA Jenkins
> UPGRADES of versions to align to JBEAP 7.2 - 1st upgrades

- ip-bom/pom.xml
- pom.xml
tested with all updates on RHBA Jenkins
> UPGRADES of versions to align to JBEAP 7.2 - 2nd upgrades

- pom.xml
Signed-off-by: Piotr Szubiakowski <pszubiak@redhat.com>
> Upgrade to Wildfly 14.

- pom.xml
> upgrade org.apache.neethi

- pom.xml
JBEAP 7.2. alignment
two test fail during the tests: 
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/Test-jobs/job/kieAllBuild-and-jboss-ip-bom-upgrade-org.apache.commons/lastCompletedBuild/testReport/
> upgrade org.apache.commons

- pom.xml
> RHPAM-1873: upgraded org.apache.cxf

- ip-bom/pom.xml
- pom.xml
> RHPAM-1874: upgraded org.infinispan

- ip-bom/pom.xml
- pom.xml
All upgrades were tested on Jenkins. The build was SUCCESSFUL
> Jbeap7.2 alignment

- pom.xml
> PLANNER-1436: phase 1
