pom.xml
This is a new PR about the upgrade of version.org.jboss.as from 7.4.0.Final-redhat-19 to 7.5.0.Final-redhat-17.
Normally we don't like to have any -redhat versions in jboss-ip-bom - but for this one there is an exception.
=> upgrade org.jboss.as

pom.xml
This is for upgrade mvel to 2.2.4.Final from 2.2.2.Final since droolsjbpm start to use 2.2.4.Final.
Let's make this consistent across jboss products.
=> Upgrade mvel to 2.2.4.Final

ip-bom/pom.xml, pom.xml
These deps are taken from: 
http://<internal-repo>/latest/maven/org/jboss/as/jboss-as-parent/7.5.0.Final-redhat-17/jboss-as-parent-7.5.0.Final-redhat-17.pom (EAP 6.4) 
http://anonsvn.jboss.org/repos/jbossws/stack/cxf/tags/jbossws-cxf-4.3.4.Final/pom.xml (EAP 6.4 jbossws version)
bXms 6.1 will be based on EAP 6.4, and AFAICT, 6.4 is based on the 7.5.0.x build of jboss-as.
=> Adding webservices (based on jbossws/cxf) dependencies, based on EAP 6.4

ip-bom/pom.xml, pom.xml
Discussed in ip-dev ,the ironjacamar artifacts are not shipped in IP products. They are only test artifacts for Modeshape project. So it should be good to remove them from ip bom . This will remove the efforts to synchronize the ironjacamar version with EAP or other if applicable.
=> Remove ironjacamar artifacts since it's shipped  in IP products

ip-bom/pom.xml, pom.xml
The `picketbox` version is based on what's in EAP 6.4 ER1.
=> Added jboss-as-security and picketbox artifacts.

ip-bom/pom.xml
As of the 4.2 release of httpcomponents, they have a fluent interface (documentation [here](http://hc.apache.org/httpcomponents-client-ga/tutorial/html/fluent.html)) which is easier to use and which KIE/drools/jbpm would like to use in the integration tests.
=> Added org.apache.httpcomponents:fluent-hc dependency

ip-bom/pom.xml
since cxf.version is not any more declared in jboss-integration-platform-bom/pom-xml two artifacts in jboss-integration-platform-bom/ip-bom/pom-xml that were still using this version had to be modified to use version.org.apache.cxf
=> changed version name

ip-bom/pom.xml, pom.xml
jBPM will be starting to use the Criteria API in community 6.3+, and the jpa-modelgen is a helpful tooling jar for that.
=> Added dep mgmt for org.hibernate:hibernate-jpamodelgen

pom.xml
alignment to EAP 6.4:
In EAP 6.4 it is used resteasy 2.3.10.Final-redhat-1.
=> upgrade resteasy from 2.3.7.Final to 2.3.10.Final

pom.xml
We need a bump from saxon 9.5.1-2 to 9.5.1-5 to support Java 1.8.     This details the issues that saxon 9.5.1-*<9.5.1-5 have with Java 1.8 :+1: 
https://saxonica.plan.io/issues/1944
=> SWITCHYARD-2504 camel-saxon quickstart fails on Java 1.8

pom.xml
Upgrading camel version to 2.15.2. Also update com.sun.xml.bind from 2.2.5 to 2.2.11 to avoid JAXB related issue camel-2.15 hit.
=> SWITCHYARD-2624 Upgrade integration-platform-bom to use Camel 2.15.x

pom.xml
* 1.7.4 adds the possibility to exclude whole classes from the
check (e.g. generated Errai marshalling classes)
=> Upgrade illegal-transitive-dependency-check from 1.7.2 to 1.7.4

ip-bom/pom.xml, pom.xml
EAP 6.4.2 uses org.apache.cxf:cxf-api:2.7.16
=> upgraded to <version.org.apache.cxf>2.7.16 to align with EAP 6.4.2

pom.xml
the most equal version available in Nexus.
For some reason there is not a 7.5.2.Final - only the 7.5.2.Final-redhat-2
=> upgraded org.jboss.as to 7.5.2.Final-redhat-2 to align with EAP 6.4.2

pom.xml
Downgrade jgroups to 3.2.13.Final.     3.2.14.Final was a Red Hat only productization release and there are no plans to release this tag publicly to community.
=> Downgrade jgroups to 3.2.13.Final - there is no public 3.2.14.Final.

pom.xml
Downgrade <version.org.jboss.jbossts.xts> from 4.17.30.Final to 4.17.29.Final.    
There is no publicly released maven artifact for jbossxts-4.17.30.Final.jar, but there is a jbossxts-4.17.29.Final.jar.    The requirement for 4.17.30.Final is causing build issues on SwitchYard's end. 
Note : there is a jbossxts-4.17.30.Final-redhat-1.jar but I don't believe we're supposed to use product releases here in the BOM, especially ones that don't exist in public repositories.
=> downgrade xts to 4.17.29.Final

ip-bom/pom.xml, pom.xml
* removed deps are either banned uberjars or they
are not available in any of the following repos:
- Maven Central (https://repo1.maven.org/maven2)
- JBoss.org Nexus (https://repository.jboss.org/nexus/content/groups/public)
- Red Hat Public Product Repo (https://maven.repository.redhat.com/ga)
=> Remove non-existing dependencies + banned uberjars

ip-bom/pom.xml
* jboss-annotations-api_1.1_spec should be use instead
=> Exclude javax.annotation:jsr250-api from weld-core and weld-se-core

ip-bom/pom.xml
* IP projects should be using JBoss Spec jars and not the different javax.* jars.
This fixes the issue at top-level, so it does not need to be done individually
at project levels.
=> Exclude javax.transaction:jta from Bitronix

pom.xml
The main reason for this change is to get rid of `dom4j` dependency. Version `3.10.1` depends on it, but it the dependency was removed in `3.13` (or maybe in earlier version). `dom4j` brings additional xml-related deps which then leads to duplicated classes with same FQN:
Dependency tree of version `3.10.1`:
```
[INFO] +- org.apache.poi:poi-ooxml:jar:3.10.1:compile
[INFO] |  +- org.apache.poi:poi-ooxml-schemas:jar:3.10.1:compile
[INFO] |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.3.0:compile
[INFO] |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |  \- dom4j:dom4j:jar:1.6.1:compile
[INFO] |     \- xml-apis:xml-apis:jar:1.3.04:compile
[INFO] +- org.apache.poi:poi:jar:3.10.1:compile
```
And the duplicated classes found:
```
Duplicate classes found:
Found in: …
```
=> Upgrade Apache POI from 3.10.1 to 3.13

pom.xml
* new versions are still JDK6 compatible (verified by `javap -v <class-from-jar>` and looking at major version)
* these mocking libraries have inter-dependencies,
so it wasn't possible to ugprade just powermock
(as that was the one causing issues on JDK8). These
versions are known to work together
=> Upgrade mocking deps to make them compatible with JDK8

pom.xml
This is the complete diff between version 16 and 19. Bunch of plugin updates + few additional fixes.
https://github.com/jboss/jboss-parent-pom/compare/jboss-parent-16...jboss-parent-19
The reason I am proposing this change is to get rid of some of the local overrides we have in our parent, since they are already present in the jboss-parent. I believe this should be a safe change, but it would be probably a good idea to try this locally with our projects, just to be sure.
=> Upgrade jboss-parent from 16 to 19

ip-bom/pom.xml, pom.xml
* libraries should not depend on specific logging
implementations, but rather logging API (like SLF4J)
and the user's of those libs pick the actual
implementation (be it logback, log4j or JUL).
There are probably other jars which drag in log4j, perhaps we should exclude the log4j from all those as well (as a subsequent PR)....
=> Exclude log4j coming from helix-core

ip-bom/pom.xml, pom.xml
* this means the IP BOM will be buildable only by Java 8+
Once merged, I will create 6.0.x branch which would be the same as master, minus this commit.
=> Upgrade version to 7.0.0-SNAPSHOT + set source/target levels to Java 8

pom.xml
* version 3.18.2-GA fixes the issue described in http://stackoverflow.com/questions/30313255/reflections-java-8-invalid-constant-type
EAP uses different version, but we really need this fix in. I will talk to WildFly/EAP guys if they could upgrade as well, so that we would be aligned.
=> Upgrade org.javassist:javassist to 3.18.2-GA to fix issue on Java 8

pom.xml
Upgrade the version of Camel from 2.15.2 to 2.16.2 on the 6.0.x branch.
=> Upgrade Camel from 2.15.2 to 2.16.2.

ip-bom/pom.xml, pom.xml
As far as I know, at least errai and uberfire-extensions are using keycloak.
It should be easier to keep keycloak version consistent between jboss-integration projects.
=> BZ-1309248 Add keycloak into jboss-integration-bom

ip-bom/pom.xml, pom.xml
this will fix the BZ 1312172 and 1312175
we have should release the next jboss-ip-bpm 6.0.3.Final to have this fix in the next 6.4.x release
=> upgraded version.org.beanshell from 2.0b5 to 2.0b6

pom.xml
(cherry picked from commit ae4b6bfc562751d53fe2caa1695ccb743841787a)
=> Upgrade commons-collections from 3.2.1 to 3.2.2 to avoid CVE-2015-8103

pom.xml
(cherry picked from commit f9bb985797cfee9f3f407cba3e371e374a9c140d)
=> Upgrade commons-math3 from 3.2 to 3.4.1 (Backport PR)

pom.xml
* 1.1.3 depends on slf4j-api 1.7.7
(used by ip-bom as well)
=> Upgrade Logback from 1.0.9 to 1.1.3

ip-bom/pom.xml, pom.xml
GwtMockito 1.1.6 allows removal of temporary exclusion https://github.com/jboss-integration/jboss-integration-platform-bom/blob/master/ip-bom/pom.xml#L256. See https://github.com/google/gwtmockito#version-history
Furthermore GwtMockito 1.1.6 supports use of a prototype JUnit Test Runner (see https://github.com/romartin/lienzo-mockito); needed for Drools 7.x unit tests.
=> Upgrade GwtMockito to 1.1.6

ip-bom/pom.xml, pom.xml
* these are the versions used by WFLY10/EAP7
=> Upgrade JAXRS API from 1.1 to 2.0 + RestEasy from 2.3.10.Final to 3.0.16.Final

ip-bom/pom.xml, pom.xml
* the artifactIds were changed as well (e.g. servlet-api-3.0
vs servlet-api-3.1) so this will require fixes in the child
POMs
=> Align several 'org.jboss.spec.javax.*' deps with WFLY10/EAP7

pom.xml
* there are some API changes between the releases, most notably
regarding Hooks. See https://wiki.eclipse.org/JGit/New_and_Noteworthy
for more info
@porcelli, @ederign do you agree with this JGit upgrade? I briefly looked at the release notes and there are quite a few bug fixes and also some performance improvements, so I think it would be worth the effort. I also tried to run the UF build with the new version and after few minor fixes all the tests are passing.
=> Upgrade JGit from 3.7.1.201504261725-r to 4.3.1.201605051710-r

ip-bom/pom.xml, pom.xml
* only WildFly 10+ is supported on branch 7.x, so no one
should be using these old artifacts
=> Replace 'org.jboss.as' deps with 'org.wildfly' ones

pom.xml
Version 3.5.2 contains two useful fixes related to Iterator asserts.
=> Upgrade assertj-core from 3.3.0 to 3.5.2

pom.xml
These versions will also be used by EAP 7.1 (when it gets released).
=> Upgrade Weld to 2.4.1.Final + Weld API to 2.4.Final

pom.xml
The 'incubating' means the freemarker projects was moved
to Apache foundation and is in incubating period.
=> Upgrade freemarker from 2.3.19 to 2.3.25-incubating

pom.xml
These new versions are already built from source in Brew.
=> Upgrade versions of Ant to 1.8.4 and iText to 2.1.7.

pom.xml
Javassist 3.20.0+ required by Hibernate 5.1.x
=> Upgrade Javassist from 3.18.2-GA to 3.20.0-GA

pom.xml
Hey @manstis 
Here is the lienzo-core upgrade for the IP-BOM.
Thanks!
Roger
=> JBPM-5595: Upgrade lienzo-core to version 2.0.286-RELEASE.

pom.xml
upgraded
<version.org.apache.cxf>
<version.org.jboss.resteasy>
<version.org.jboss.spec.javax.servlet.jstl.jboss-jstl-api_1.2_spec>
<version.org.jboss.xnio>
<version.org.jboss.ws.spi>
<version.org.jboss.ws.cxf>
<version.org.jgroups>
<version.org.picketbox>
<version.org.picketlink>
<version.xerces>
=> upgraded dependencies to align to eap 7.0.5.GA-redhat-2

ip-bom-deps-available-test/ip-bom-deps-available-test-settings.xml
Adding the Maven Central as a first repository means that Maven
will primarily contact that repo when looking for deps. Since most of
the deps are available there (and Maven Central is blazing fast) the
CI build gets a huge speedup.
=> Reorganize repos in settings.xml to speed up CI build

pom.xml
From 1.7 to 1.9 some security issues have been fixed
https://xmlgraphics.apache.org/security.html
=> Upgrade Batik to version 1.9

pom.xml
*Upgrade the logback version from 1.1.3 to 1.2.3
According to CVE-2017-5929 and RHBPMS-4660, the bug is fixed in 1.2.0. The latest version is 1.2.3
*Upgrade the slf4j version from 1.7.7 to 1.7.25 to keep up with the logback 1.2.3 as suggested.
=> Upgrade logback version to 1.2.3 and upgrade slf4j version to 1.7.25

pom.xml
*Upgrade the logback version from 1.1.3 to 1.2.3
according to CVE-2017-5929 RHBPMS-4660 bug is fixed in 1.2.0, but the latest version is 1.2.3
*Upgrade the slf4j version from 1.7.7 to 1.7.25 to keep up with the logback 1.2.3
=> Upgrade the logback version to 1.2.0 and slf4j version to 1.7.22 for 7.0.x

ip-bom/pom.xml
fixing wrong definition of batik-extension see error from CI test of https://github.com/kiegroup/jbpm-designer/pull/700
=> JBPM-6274: fix of managed artifactId for batik-extension

ip-bom/pom.xml, pom.xml
move of xmlgraphics-commons to IP-BOM and upgrade to 2.2
This resulted from discussion in https://github.com/kiegroup/jbpm-designer/pull/700#issuecomment-346700994 and https://github.com/kiegroup/jbpm-designer/pull/700#issuecomment-346700994 comments.
=> JBPM-6274: continuation of batik upgrade

pom.xml
See [JBPM-6102](https://issues.jboss.org/browse/JBPM-6102)
**Note**: please merge together or after these other ones: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/629 and https://github.com/kiegroup/kie-wb-common/pull/1309.
=> JBPM-6102: Upgrade lienzo artifacts to version 2.0.293-RELEASE

pom.xml
Hi, @mareknovotny,
here is the upgrade of ShrinkWrap resolver to the version 3.1.0 which uses newest Maven Artifact Resolver instead of Aether and fixes issues with downloading optional dependencies when generating archives using Arquillian.
Thanks.
=> Upgrade ShrinkWrap Resolver to 3.1.0

pom.xml
In Fedora is much easier to have protobufc 3.6 installed than 2.6 and from my experiments drools works without problem with that. I hope that JBPM does that also
=> Updated protobuf to 3.6.1

pom.xml
I updated the version of org.eclipse.bpmn2. this is to use the new version.
=> JBPM-6794 - updating eclipse.bpmn2 version

ip-bom/pom.xml, pom.xml
Hi @mbiarnes @mareknovotny,
here is the PR we discussed which aligns jaxws-api and jaxb-api with Wildfly. After ip-bom of version 8.4.0.Final is released, we can also merge PRs which are waiting across kiegroup repositories.
Thanks for help!
=> Align JAXB and JAXWS APIs with Wildfly

pom.xml
I upgraded JavaAssist dependency to fix GwtMockito issues on Java 11 (see exception below). I tested it on Stunner repository and this error is fixed.
Full downstream build tested there: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/934
<details>
<summary>ClassNotFoundException in GwtMockito</summary>
<pre>Error Message
caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
Stacktrace
java.lang.ClassNotFoundException: caught an exception while obtaining a class file for com.google.gwtmockito.GwtMockito
at javassist.Loader.findClass(Loader.java:357)
at com.google.gwtmockito.GwtMockitoTestRunner$GwtMockitoClassLoader.findClass(GwtMockitoTestRunner.java:421)
at javassist.Loader.loadClass(Loader.java:309)
at …
=> JBPM-8029: Align deps to support GwtMockito in Java11
